name: Test

on:
  push:
     branches:
       - main
  pull_request:
  workflow_dispatch:

jobs:
  setup-simple:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Debspawn Setup
        uses: ./setup
        with:
          suite: stable
          cache: true

  setup-with-packages:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Debspawn Setup (with packages)
        uses: ./setup
        with:
          suite: stable
          cache: true
          packages: >-
            curl
            git
            ca-certificates
